server.port=4000
spring.application.name=cuarto
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/alumno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver